_target_: src.models.unet_module.UnetModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.unet.Unet
  in_chans: 1
  out_chans: 1
  chans: 32
  num_pool_layers: 4
  drop_prob: 0.0


# compile model for faster training with pytorch 2.0
compile: false
