_target_: src.models.varnet_module.VarnetModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.varnet.Varnet
  num_cascades: 12
  pools: 4
  chans: 18
  sens_pools: 4
  sens_chans: 8


# compile model for faster training with pytorch 2.0
compile: false
