defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_step_{step}"
  monitor: "val/psnr"
  mode: "max"
  save_top_k: 5
  save_last: true
  auto_insert_metric_name: false
  verbose: true

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
